require: rubocop-rails

AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails/DynamicFindBy:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false
