version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - '.env.web'
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

