name: Ruby tests

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chrome driver
      uses: nanasess/setup-chromedriver@v1.0.1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
