name: Ruby tests

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chrome driver
      uses: nanasess/setup-chromedriver@v1.0.1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    # - name: Set up Postgres
    #   uses: harmon758/postgresql-action@v1

    - name: Install Postgres dependencies
      run: sudo apt-get -yqq install libpq-dev

    - name: Setup test database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: myapp
      run: bundle exec rails db:setup

    - name: Run tests
      env:
        # # The hostname used to communicate with the PostgreSQL service container
        # POSTGRES_HOST: postgres
        # # The default PostgreSQL port
        # POSTGRES_PORT: 5432
        RAILS_ENV: test
      run: bundle exec rake
