name: Ruby tests

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-20.04

    services:

      postgres:
        image: postgres

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chrome driver
      uses: nanasess/setup-chromedriver@v1.0.1

    - name: Install Postgres dependencies
      run: sudo apt-get install libpq-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run tests
      env:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        PGUSER: postgres
      run: bundle exec rake
